version: "1"
services:
  test:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./oci-cli-res:/root/.oci
      - ./oci-fn-res:/root/.fn
      - ~/.kube/config:/root/.kube/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_PWD=dlyUxuZ3(>2MEk0(XtKp