api-url: https://functions.us-ashburn-1.oraclecloud.com
oracle.compartment-id: ocid1.tenancy.oc1..aaaaaaaaxaut52vhoboa3dsy7vzwtszofw4wwb32dmvxl7wxgvdtr47evc5a
oracle.profile: DEFAULT
provider: oracle
registry: iad.ocir.io/idzrfcii0n3e/test
